-- require("partiallypractical/remap")
-- require("partiallypractical/set")
require("partiallypractical/options")
require("partiallypractical/plugin-setup")
require("partiallypractical/language-client")
require("partiallypractical/telescope")
require("partiallypractical/plugin-config")
require("partiallypractical/snippets")
